{% set name = "pkbar" %}
{% set version = "0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pkbar-{{ version }}.tar.gz
  sha256: 3a6c389688cfa70c84433171ece71098c7f7181de3ba8375019de5713501ef15
  patches:
    - patches/gh0007.patch

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - pkbar
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/yueyericardo/pkbar
  summary: Keras Progress Bar for PyTorch
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mikemhenry
